services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/__pycache__/
      - ./logs:/logs
    environment:
      - GOOGLE_GEMINI_API_KEY
      - GOOGLE_MAPS_API_KEY
      
